### ISSUE TITLE
this module as dependency

### ISSUE THREAD

**Issue by ksjogo** [lunaryorn/emacs-module.rs#2]
Regarding the git use-case:
Could we upload this module as a kind of base emacs module to crates?
The pub stuff from here will also be exposed, when another module statically links this module?
How could the init function be hooked?

**Comment by lunaryorn** [comment]
@ksjogo We could definitely turn this into a library for other modules to depend upon, providing the proper initialisation and a nice wrapper around the Emacs module API.

But that's really a future story; my plan currently is to get it into a solid state first.

**Comment by vermiculus** [comment]
Agree; this project (while exciting!!) isn't ready for primetime. @ksjogo, I think we should either continue exploring emacs-libgit2 in C or take some time to familiarize ourselves with [the `git2-rs` bindings](https://github.com/alexcrichton/git2-rs).

Having this as a workable dependency would absolutely *boon* emacs module development, I think 👍

**Comment by lunaryorn** [comment]
@vermiculus Agreed about the first part, not so sure about the second.  Depends on whether we can deliver a solid packaging story for Rust modules.  But maybe we can that this repo that far.

But still, let me get the basics straight first :wink:

**Comment by vermiculus** [comment]
> But still, let me get the basics straight first

Naturally 😄

**Comment by lunaryorn** [comment]
@ksjogo Why did you publish this code to crates.io at https://crates.io/crates/emacs-rust-module-base?!

**Comment by ksjogo** [comment]
Because I tried building it as a dependency to better understand crates.

**Comment by vermiculus** [comment]
Publishing is traditionally a step for the maintainer to take 😕

**Comment by lunaryorn** [comment]
I don't mind; I just wondered.  I'll be publishing the module when it's ready.  I'm trying to make nice API around it.

**Comment by dsvensson** [comment]
@lunaryorn any update on that nice API you mentioned there?

**Comment by lunaryorn** [comment]
@dsvensson I'm no longer using Emacs, and I do not work on this anymore.  Feel free to fork.

**Comment by vermiculus** [comment]
> I'm no longer using Emacs

😮 I'll read [your post on the matter](http://www.lunaryorn.com/posts/bye-bye-emojis-emacs-hates-macos.html) and comment there.

**Comment by lunaryorn** [comment]
@vermiculus That post is only partially related to my decision.
