### ISSUE TITLE
blog post about writing emacs modules in rust ?

### ISSUE THREAD

**Issue by sam217pa** [lunaryorn/emacs-module.rs#3]
I tend to think that this new Emacs module support is _the_ killer feature of emacs 25, but I don't have the beginning of an idea about how to make use of it, and how developper could use it.

I'd be very interested in a tuto-like post about writing emacs modules in Rust or any other GPL compatible language, how it could be of use and in the more general sense what to do with it.

Regards, and thanks for your nice work on flycheck !

**Comment by lunaryorn** [comment]
I'll definitely write a blog post about it; already had a card for it on the "Bootstrap" project board :wink:

But I'll iron out the kinks first; there's still a bit to do before this is a solid example.
